### ISSUE TITLE
Detailed description of build process

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-mobile-app#1]
I would like to request a detail description (step by step) how to build, bundle and publish the app.

**Comment by sschiessl-bcp** [comment]
@syalon

**Comment by qingfengzh** [comment]
@sschiessl-bcp
Android Test & Build & Sign
https://github.com/bitshares/bitshares-mobile-app/blob/master/android_compile.md

**Comment by syalon** [comment]
Hello @sschiessl-bcp .
We updated the new build script and it is now easier to compile.

Compile the native library reference: [Click to view](https://github.com/bitshares/bitshares-mobile-app/blob/master/native_lib_compile.md).

Android Build & Test Reference: [Click to view](https://github.com/bitshares/bitshares-mobile-app/blob/master/android_compile.md).
