### ISSUE TITLE
Faucet JSON Post Request Format Different from Official Bitshares UI

### ISSUE THREAD

**Issue by bangzi1001** [bitshares/bitshares-mobile-app#2]
The Bitshares Mobile App faucet JSON post request format to register new account is different from Bitshares UI which mean if developer change faucet in Bitshares Mobile App to https://faucet.bitshares.eu/, registration will fail. It will be easier for developer/marketers if Bitshares Mobile App can follow Bitshares UI.

Reference forOfficial Bitshares UI faucet :
https://bitshares.eu/referral/info/api
https://github.com/bitshares/bitshares-ui/blob/9782057d00830bcf2ca72f37ef1d3da4fce5dc6d/app/actions/WalletActions.js#L119

**Comment by syalon** [comment]
Well, this will be compatible later, and the version of the subsequent official website will be replaced by the faucet provided by BBF.

**Comment by syalon** [comment]
Already supported, the master branch has been merged.
