### ISSUE TITLE
Price has too low precision (BTS/BTC)

### ISSUE THREAD

**Issue by serdrdoor** [bitshares/bitshares-mobile-app#5]
http://prntscr.com/taodem
![image](https://user-images.githubusercontent.com/11815105/86401547-15417280-bcb3-11ea-91b9-2b7b69cf7cf1.png)

**One of the main pairs: BTS / BTC**
**1.** Precisions in the orderBook  not allow you to comfortably trade.
Because does not allow to put in the field more than 6 decimal places for BTC.
But BTC has 8 digits.

**2.** In addition to trading, looking into a orderBook is not informative, as it’s not clear where the orders of others traders are placed, because even  if you click on them (line order), the price will be conversion with cropping up to 6 characters.
Screenshot above.

**3.** The same problem applies to other assets, with a rather low price in BTC. For BTC, it is necessary to have an precision of 8 digits, in my opinion.

**Comment by syalon** [comment]
What's the app version?

**Comment by serdrdoor** [comment]
> What's the app version?
last 6.0
![image](https://user-images.githubusercontent.com/11815105/86495669-fca08d80-bd82-11ea-8e68-4a5b5a03113a.png)

**Comment by syalon** [comment]
fixed in v6.1
